# Copyright 2014-2016 Spotify AB
# Copyright 2016-2019 The Last Pickle Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ITs with Sidecar Mode

on:
  push:
    paths-ignore:
      - "untagged-.**"
      - "master-snapshot.**"
#  pull_request:
#    paths-ignore:
#      - "untagged-.**"
#      - "master-snapshot.**"

jobs:
  its-sidecar:
    name: Run ITs
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.4
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ''
          # this replaces the manual reaper creation
          POSTGRES_DB: reaper
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      matrix:
        cassandra-version: [2.1.20, 2.2.13, 3.0.17, 3.11.3, 'github:apache/trunk']
        storage-type: [cassandra, postgresql]
        test-type: [sidecar]
        grim-max: [1]
        grim-min: [1]
        # all versions but trunk have the same cucumber options, but we can't declare that more effectively (yet)
        include:
          - cassandra-version: 2.1.20
            cucumber-options: '--tags ~@cassandra_4_0_onwards --tags @sidecar'
          - cassandra-version: 2.2.13
            cucumber-options: '--tags ~@cassandra_4_0_onwards --tags @sidecar'
          - cassandra-version: 3.0.17
            cucumber-options: '--tags ~@cassandra_4_0_onwards --tags @sidecar'
          - cassandra-version: 3.11.3
            cucumber-options: '--tags ~@cassandra_4_0_onwards --tags @sidecar'
          - cassandra-version: 'github:apache/trunk'
            cucumber-options: '--tags @sidecar'
        # sidecar test including postgres should only run with C* 3.11.3, so we exclude all other
        exclude:
          - storage-type: postgresql
            cassandra-version: 2.1.20
          - storage-type: postgresql
            cassandra-version: 2.2.13
          - storage-type: postgresql
            cassandra-version: 3.0.17
          - storage-type: postgresql
            cassandra-version: 'github:apache/trunk'
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Maven Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup CCM Cache
        uses: actions/cache@v1
        with:
          path: ~/.ccm/repository
          key: ${{ runner.os }}-ccm-${{ hashFiles('**') }}
          restore-keys: |
            ${{ runner.os }}-ccm-

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.192'
          java-package: jdk
          architecture: x64

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Setup bower
        run: npm install -g bower

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install CCM
        run: pip install pyyaml ccm

      - name: Setup CCM Cluster
        run: ./.github/scripts/configure-ccm.sh
        env:
          TEST_TYPE: ${{ matrix.test-type }}
          CASSANDRA_VERSION: ${{ matrix.cassandra-version }}
          STORAGE_TYPE: ${{ matrix.storage-type }}

      - name: Run Tests
        run: ./.github/scripts/run-tests.sh
        env:
          TEST_TYPE: ${{ matrix.test-type }}
          CASSANDRA_VERSION: ${{ matrix.cassandra-version }}
          STORAGE_TYPE: ${{ matrix.storage-type }}
          GRIM_MAX: ${{ matrix.grim-max }}
          GRIM_MIN: ${{ matrix.grim-min }}
          CUCUMBER_OPTIONS: ${{ matrix.cucumber-options }}
